In [5]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+pymysql://root:Kalai1805vk12@localhost/Customer_Churn")
df = pd.read_sql("SELECT * FROM customers_Data", engine)

In [6]:
print(df)

    customer_id  gender  tenure        contract  monthly_charges  \
0             1    Male       1  Month-to-month             70.5
1             2  Female      24        One year             80.0
2             3    Male       3  Month-to-month             90.0
3             4  Female      48        Two year             60.0
4             5    Male      12  Month-to-month             75.0
5             6  Female      36        One year             65.0
6             7    Male       5  Month-to-month             95.0
7             8  Female      60        Two year             55.0
8             9    Male      18        One year             70.0
9            10  Female       2  Month-to-month             85.0
10           11    Male      30        One year             60.0
11           12  Female       8  Month-to-month             88.0
12           13    Male      45        Two year             50.0
13           14  Female       6  Month-to-month             92.0
14           15    Male      20        One year             68.0
15           16  Female      55        Two year             58.0
16           17    Male       4  Month-to-month             97.0
17           18  Female      10  Month-to-month             82.0
18           19    Male      40        Two year             62.0
19           20  Female      15        One year             70.0
20           21    Male       2  Month-to-month             89.0
21           22  Female      28        One year             66.0
22           23    Male      50        Two year             52.0
23           24  Female       7  Month-to-month             91.0
24           25    Male      14  Month-to-month             78.0
25           26  Female      33        One year             64.0
26           27    Male      60        Two year             58.0
27           28  Female       9  Month-to-month             86.0
28           29    Male      22        One year             70.0
29           30  Female       4  Month-to-month             93.0
30           31    Male      18        One year             67.0
31           32  Female      11  Month-to-month             85.0
32           33    Male      42        Two year             55.0
33           34  Female       6  Month-to-month             96.0
34           35    Male      25        One year             72.0
35           36  Female      48        Two year             60.0
36           37    Male       3  Month-to-month             98.0
37           38  Female      16  Month-to-month             80.0
38           39    Male      38        Two year             62.0
39           40  Female      20        One year             69.0

    total_charges internet_service churn
0            70.5      Fiber optic   Yes
1          1920.0              DSL    No
2           270.0      Fiber optic   Yes
3          2880.0              DSL    No
4           900.0      Fiber optic   Yes
5          2340.0              DSL    No
6           475.0      Fiber optic   Yes
7          3300.0              DSL    No
8          1260.0              DSL    No
9           170.0      Fiber optic   Yes
10         1800.0              DSL    No
11          704.0      Fiber optic   Yes
12         2250.0              DSL    No
13          552.0      Fiber optic   Yes
14         1360.0              DSL    No
15         3190.0              DSL    No
16          388.0      Fiber optic   Yes
17          820.0      Fiber optic   Yes
18         2480.0              DSL    No
19         1050.0              DSL    No
20          178.0      Fiber optic   Yes
21         1848.0              DSL    No
22         2600.0              DSL    No
23          637.0      Fiber optic   Yes
24         1092.0      Fiber optic   Yes
25         2112.0              DSL    No
26         3480.0              DSL    No
27          774.0      Fiber optic   Yes
28         1540.0              DSL    No
29          372.0      Fiber optic   Yes
30         1206.0              DSL    No
31          935.0      Fiber optic   Yes
32         2310.0              DSL    No
33          576.0      Fiber optic   Yes
34         1800.0              DSL    No
35         2880.0              DSL    No
36          294.0      Fiber optic   Yes
37         1280.0      Fiber optic   Yes
38         2356.0              DSL    No
39         1380.0              DSL    No

In [7]:
df.to_csv("Customer_Churn.csv",index=False)

In [8]:
pd.read_csv("Customer_Churn.csv")

,customer_id,gender,tenure,contract,monthly_charges,total_charges,internet_service,churn
0,1,Male,1,Month-to-month,70.5,70.5,Fiber optic,Yes
1,2,Female,24,One year,80.0,1920.0,DSL,No
2,3,Male,3,Month-to-month,90.0,270.0,Fiber optic,Yes
3,4,Female,48,Two year,60.0,2880.0,DSL,No
4,5,Male,12,Month-to-month,75.0,900.0,Fiber optic,Yes
5,6,Female,36,One year,65.0,2340.0,DSL,No
6,7,Male,5,Month-to-month,95.0,475.0,Fiber optic,Yes
7,8,Female,60,Two year,55.0,3300.0,DSL,No
8,9,Male,18,One year,70.0,1260.0,DSL,No
9,10,Female,2,Month-to-month,85.0,170.0,Fiber optic,Yes
10,11,Male,30,One year,60.0,1800.0,DSL,No
11,12,Female,8,Month-to-month,88.0,704.0,Fiber optic,Yes
12,13,Male,45,Two year,50.0,2250.0,DSL,No
13,14,Female,6,Month-to-month,92.0,552.0,Fiber optic,Yes
14,15,Male,20,One year,68.0,1360.0,DSL,No
15,16,Female,55,Two year,58.0,3190.0,DSL,No
16,17,Male,4,Month-to-month,97.0,388.0,Fiber optic,Yes
17,18,Female,10,Month-to-month,82.0,820.0,Fiber optic,Yes
18,19,Male,40,Two year,62.0,2480.0,DSL,No
19,20,Female,15,One year,70.0,1050.0,DSL,No
20,21,Male,2,Month-to-month,89.0,178.0,Fiber optic,Yes
21,22,Female,28,One year,66.0,1848.0,DSL,No
22,23,Male,50,Two year,52.0,2600.0,DSL,No
23,24,Female,7,Month-to-month,91.0,637.0,Fiber optic,Yes
24,25,Male,14,Month-to-month,78.0,1092.0,Fiber optic,Yes
25,26,Female,33,One year,64.0,2112.0,DSL,No
26,27,Male,60,Two year,58.0,3480.0,DSL,No
27,28,Female,9,Month-to-month,86.0,774.0,Fiber optic,Yes
28,29,Male,22,One year,70.0,1540.0,DSL,No
29,30,Female,4,Month-to-month,93.0,372.0,Fiber optic,Yes
30,31,Male,18,One year,67.0,1206.0,DSL,No
31,32,Female,11,Month-to-month,85.0,935.0,Fiber optic,Yes
32,33,Male,42,Two year,55.0,2310.0,DSL,No
33,34,Female,6,Month-to-month,96.0,576.0,Fiber optic,Yes
34,35,Male,25,One year,72.0,1800.0,DSL,No
35,36,Female,48,Two year,60.0,2880.0,DSL,No
36,37,Male,3,Month-to-month,98.0,294.0,Fiber optic,Yes
37,38,Female,16,Month-to-month,80.0,1280.0,Fiber optic,Yes
38,39,Male,38,Two year,62.0,2356.0,DSL,No
39,40,Female,20,One year,69.0,1380.0,DSL,No

In [10]:
df.notnull().sum()
print(df)

    customer_id  gender  tenure        contract  monthly_charges  \
0             1    Male       1  Month-to-month             70.5
1             2  Female      24        One year             80.0
2             3    Male       3  Month-to-month             90.0
3             4  Female      48        Two year             60.0
4             5    Male      12  Month-to-month             75.0
5             6  Female      36        One year             65.0
6             7    Male       5  Month-to-month             95.0
7             8  Female      60        Two year             55.0
8             9    Male      18        One year             70.0
9            10  Female       2  Month-to-month             85.0
10           11    Male      30        One year             60.0
11           12  Female       8  Month-to-month             88.0
12           13    Male      45        Two year             50.0
13           14  Female       6  Month-to-month             92.0
14           15    Male      20        One year             68.0
15           16  Female      55        Two year             58.0
16           17    Male       4  Month-to-month             97.0
17           18  Female      10  Month-to-month             82.0
18           19    Male      40        Two year             62.0
19           20  Female      15        One year             70.0
20           21    Male       2  Month-to-month             89.0
21           22  Female      28        One year             66.0
22           23    Male      50        Two year             52.0
23           24  Female       7  Month-to-month             91.0
24           25    Male      14  Month-to-month             78.0
25           26  Female      33        One year             64.0
26           27    Male      60        Two year             58.0
27           28  Female       9  Month-to-month             86.0
28           29    Male      22        One year             70.0
29           30  Female       4  Month-to-month             93.0
30           31    Male      18        One year             67.0
31           32  Female      11  Month-to-month             85.0
32           33    Male      42        Two year             55.0
33           34  Female       6  Month-to-month             96.0
34           35    Male      25        One year             72.0
35           36  Female      48        Two year             60.0
36           37    Male       3  Month-to-month             98.0
37           38  Female      16  Month-to-month             80.0
38           39    Male      38        Two year             62.0
39           40  Female      20        One year             69.0

    total_charges internet_service churn
0            70.5      Fiber optic   Yes
1          1920.0              DSL    No
2           270.0      Fiber optic   Yes
3          2880.0              DSL    No
4           900.0      Fiber optic   Yes
5          2340.0              DSL    No
6           475.0      Fiber optic   Yes
7          3300.0              DSL    No
8          1260.0              DSL    No
9           170.0      Fiber optic   Yes
10         1800.0              DSL    No
11          704.0      Fiber optic   Yes
12         2250.0              DSL    No
13          552.0      Fiber optic   Yes
14         1360.0              DSL    No
15         3190.0              DSL    No
16          388.0      Fiber optic   Yes
17          820.0      Fiber optic   Yes
18         2480.0              DSL    No
19         1050.0              DSL    No
20          178.0      Fiber optic   Yes
21         1848.0              DSL    No
22         2600.0              DSL    No
23          637.0      Fiber optic   Yes
24         1092.0      Fiber optic   Yes
25         2112.0              DSL    No
26         3480.0              DSL    No
27          774.0      Fiber optic   Yes
28         1540.0              DSL    No
29          372.0      Fiber optic   Yes
30         1206.0              DSL    No
31          935.0      Fiber optic   Yes
32         2310.0              DSL    No
33          576.0      Fiber optic   Yes
34         1800.0              DSL    No
35         2880.0              DSL    No
36          294.0      Fiber optic   Yes
37         1280.0      Fiber optic   Yes
38         2356.0              DSL    No
39         1380.0              DSL    No

In [11]:
df['churn'].value_counts()

churn
No     22
Yes    18
Name: count, dtype: int64

In [12]:
pd.crosstab(df['contract'], df['churn'])

churn           No  Yes
contract
Month-to-month   0   18
One year        12    0
Two year        10    0